#! /usr/bin/env bash

docker.rm.unused_images(){
    docker system prune "$@"
}

docker.ls.container(){
    docker container ls -a "$@"
}

docker.rm.stopped_containers(){
    docker container prune "$@"
}


# eval "${x @bash/std}"
# eval "${x @bash/std/str}"
# eval "${x @bash/std/regex}"

# eval "${x @bash/docker}"
