#! /usr/bin/env bash

git remote remove gitee 2>/dev/null
git remote add gitee git@gitee.com:x-bash/get.git

git remote remove github 2>/dev/null
git remote add github git@github.com:x-bash/get.git

git push gitee gitee
git push github gitee

git push github main
git push gitee main
